### ISSUE TITLE
Strange thumbnail differences between small and large

### ISSUE THREAD

**Issue by warmerdam** [warmerdam/landsat_ingestor#1]
These small and large thumbnails for the same landsat scene have hugely different radiometric properties.  Why?  Possibly just a vagarity of how the sampling happens? 

https://s3-us-west-2.amazonaws.com/landsat-pds/L8/227/067/LC82270672015002LGN00/LC82270672015002LGN00_thumb_small.jpg

https://s3-us-west-2.amazonaws.com/landsat-pds/L8/227/067/LC82270672015002LGN00/LC82270672015002LGN00_thumb_large.jpg

**Comment by celoyd** [comment]
## The problem

I think we’re seeing one or both of these effects that make histograms unstable over resizing:

1. Assuming `average` resampling, as an image is reduced, individual pixels will tend to approach the overall mean value of the image. (In the extreme case, when you’ve reduced to a single pixel, it is the average value.)
Therefore, as an image gets smaller, its histogram will tend to narrow.

2. As a Landsat image is reduced, a higher fraction of pixels will have contributions from both data and nodata pixels. This will tend to smear the left-edge histogram spike that represents “clean” nodata pixels, proportional to resizing.

Problem 2 could be solved by using masks, but that would leave problem 1, which as far as I can see is inherent to any kind of resizing (other than `nearest` maybe).

## A solution

I think the best way to do this is to only measure the histogram once. Resizing the smaller image from the larger one would also work, and would be slightly faster, but would make it slightly less sharp.

[I expressed this mostly through reorganizing the existing code.](https://github.com/warmerdam/landsat_ingestor/pull/4) Please test and rework as you see fit – I tested it on 3 scenes I had lying around and nothing more.

**Comment by warmerdam** [comment]
I've confirmed the results are consistent for at least once scene:

https://s3-us-west-2.amazonaws.com/landsat-pds/L8/016/017/LC80160172015012LGN00/index.html

(despite the unfortunate purple snow)

Thanks!
